[package]
authors = ["anderejd <rajder@gmail.com>"]
name = "treesum"
version = "0.1.0"

[dependencies]
sha1 = "0.6.0"
walkdir = "2.1.4"
env_logger = "0.5.9"
log = "0.4.1"
parallel-iterator = "0.1.2"

#[profile.debug]
#panic = "abort"

#[profile.release]
#panic = "abort"

