[package]
authors = ["anderejd <rajder@gmail.com>"]
name = "treesum"
version = "0.1.0"

[dependencies]
sha1 = "0.2.0"
walkdir = "2.0.1"

[dependencies.sgiter]
git = "https://github.com/anderejd/sgiter"
