[package]
authors = ["anderejd <rajder@gmail.com>"]
name = "treesum"
version = "0.1.0"

[dependencies]
sha1 = "0.6.0"
walkdir = "2.1.4"

[dependencies.sgiter]
git = "https://github.com/anderejd/sgiter"
#path = "../sgiter"

