[package]
name = "treesum"
version = "0.1.0"
authors = ["anderejd <rajder@gmail.com>"]

[dependencies]
sgiter = { git = "https://github.com/anderejd/sgiter" }
walkdir = "*"
sha1 = "0.2"

# [profile.release]
# debug = true

